// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    lists,
    tasks,
    steps,
    reminderJobs,
    notePages,
    noteBlocks,
    tasksList,
    tasksDay,
    tasksDue,
    stepsTask,
    notesOrder,
    noteBlocksPage,
  ];
  late final Shape0 lists = Shape0(
    source: i0.VersionedTable(
      entityName: 'lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tasks = Shape1(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_4,
        _column_5,
        _column_6,
        _column_17,
        _column_7,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 steps = Shape2(
    source: i0.VersionedTable(
      entityName: 'steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_19,
        _column_9,
        _column_11,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reminderJobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'reminder_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 notePages = Shape4(
    source: i0.VersionedTable(
      entityName: 'note_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_24,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 noteBlocks = Shape5(
    source: i0.VersionedTable(
      entityName: 'note_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index tasksList = i1.Index(
    'tasks_list',
    'CREATE INDEX tasks_list ON tasks (list_id, deleted_at, sort_order)',
  );
  final i1.Index tasksDay = i1.Index(
    'tasks_day',
    'CREATE INDEX tasks_day ON tasks (my_day_date, is_completed, deleted_at)',
  );
  final i1.Index tasksDue = i1.Index(
    'tasks_due',
    'CREATE INDEX tasks_due ON tasks (due_date, is_completed, deleted_at)',
  );
  final i1.Index stepsTask = i1.Index(
    'steps_task',
    'CREATE INDEX steps_task ON steps (task_id, deleted_at, sort_order)',
  );
  final i1.Index notesOrder = i1.Index(
    'notes_order',
    'CREATE INDEX notes_order ON note_pages (deleted_at, sort_order)',
  );
  final i1.Index noteBlocksPage = i1.Index(
    'note_blocks_page',
    'CREATE INDEX note_blocks_page ON note_blocks (page_id, deleted_at, sort_order)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get color =>
      columnsByName['color']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 4282542937',
      defaultValue: const i1.CustomExpression('4282542937'),
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'list\'',
      defaultValue: const i1.CustomExpression('\'list\''),
    );
i1.GeneratedColumn<double> _column_4(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get listId =>
      columnsByName['list_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCompleted =>
      columnsByName['is_completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isImportant =>
      columnsByName['is_important']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get myDayDate =>
      columnsByName['my_day_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dueDate =>
      columnsByName['due_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reminderAt =>
      columnsByName['reminder_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get recurrenceRule =>
      columnsByName['recurrence_rule']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nextOccurrenceId =>
      columnsByName['next_occurrence_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'list_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES lists(id)',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_important',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_important IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_day_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'due_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recurrence_rule',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'next_occurrence_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isCompleted =>
      columnsByName['is_completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES tasks(id)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get notificationId =>
      columnsByName['notification_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pending =>
      columnsByName['pending']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notification_id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE REFERENCES tasks(id)',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pending',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (pending IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pageId =>
      columnsByName['page_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get checked =>
      columnsByName['checked']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageName =>
      columnsByName['image_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get detail =>
      columnsByName['detail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expanded =>
      columnsByName['expanded']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'page_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES note_pages(id)',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'checked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (checked IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'detail',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expanded',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (expanded IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    lists,
    tasks,
    steps,
    reminderJobs,
    notePages,
    noteBlocks,
    customThemes,
    themeSettings,
    tasksList,
    tasksDay,
    tasksDue,
    stepsTask,
    notesOrder,
    noteBlocksPage,
  ];
  late final Shape0 lists = Shape0(
    source: i0.VersionedTable(
      entityName: 'lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tasks = Shape1(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_4,
        _column_5,
        _column_6,
        _column_17,
        _column_7,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 steps = Shape2(
    source: i0.VersionedTable(
      entityName: 'steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_19,
        _column_9,
        _column_11,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reminderJobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'reminder_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 notePages = Shape4(
    source: i0.VersionedTable(
      entityName: 'note_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_24,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 noteBlocks = Shape5(
    source: i0.VersionedTable(
      entityName: 'note_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 customThemes = Shape6(
    source: i0.VersionedTable(
      entityName: 'custom_themes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_34, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 themeSettings = Shape7(
    source: i0.VersionedTable(
      entityName: 'theme_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(id = 1)',
        'CHECK((active_custom_theme_id IS NULL)!=(active_preset_id IS NULL))',
      ],
      columns: [_column_35, _column_36, _column_37, _column_38],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index tasksList = i1.Index(
    'tasks_list',
    'CREATE INDEX tasks_list ON tasks (list_id, deleted_at, sort_order)',
  );
  final i1.Index tasksDay = i1.Index(
    'tasks_day',
    'CREATE INDEX tasks_day ON tasks (my_day_date, is_completed, deleted_at)',
  );
  final i1.Index tasksDue = i1.Index(
    'tasks_due',
    'CREATE INDEX tasks_due ON tasks (due_date, is_completed, deleted_at)',
  );
  final i1.Index stepsTask = i1.Index(
    'steps_task',
    'CREATE INDEX steps_task ON steps (task_id, deleted_at, sort_order)',
  );
  final i1.Index notesOrder = i1.Index(
    'notes_order',
    'CREATE INDEX notes_order ON note_pages (deleted_at, sort_order)',
  );
  final i1.Index noteBlocksPage = i1.Index(
    'note_blocks_page',
    'CREATE INDEX note_blocks_page ON note_blocks (page_id, deleted_at, sort_order)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get document =>
      columnsByName['document']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'document',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get activeCustomThemeId =>
      columnsByName['active_custom_theme_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get activePresetId =>
      columnsByName['active_preset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recentColors =>
      columnsByName['recent_colors']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'active_custom_theme_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES custom_themes(id)',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'active_preset_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL DEFAULT \'preset:default\'',
      defaultValue: const i1.CustomExpression('\'preset:default\''),
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recent_colors',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    lists,
    tasks,
    steps,
    reminderJobs,
    notePages,
    noteBlocks,
    customThemes,
    themeSettings,
    focusSoundscapes,
    focusSettings,
    tasksList,
    tasksDay,
    tasksDue,
    stepsTask,
    notesOrder,
    noteBlocksPage,
  ];
  late final Shape0 lists = Shape0(
    source: i0.VersionedTable(
      entityName: 'lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tasks = Shape1(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_4,
        _column_5,
        _column_6,
        _column_17,
        _column_7,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 steps = Shape2(
    source: i0.VersionedTable(
      entityName: 'steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_19,
        _column_9,
        _column_11,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reminderJobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'reminder_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 notePages = Shape4(
    source: i0.VersionedTable(
      entityName: 'note_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_24,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 noteBlocks = Shape5(
    source: i0.VersionedTable(
      entityName: 'note_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 customThemes = Shape6(
    source: i0.VersionedTable(
      entityName: 'custom_themes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_34, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 themeSettings = Shape7(
    source: i0.VersionedTable(
      entityName: 'theme_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(id = 1)',
        'CHECK((active_custom_theme_id IS NULL)!=(active_preset_id IS NULL))',
      ],
      columns: [_column_35, _column_36, _column_37, _column_38],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 focusSoundscapes = Shape8(
    source: i0.VersionedTable(
      entityName: 'focus_soundscapes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 focusSettings = Shape9(
    source: i0.VersionedTable(
      entityName: 'focus_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(id = 1)',
        'CHECK(master_volume BETWEEN 0 AND 1)',
      ],
      columns: [_column_35, _column_39, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index tasksList = i1.Index(
    'tasks_list',
    'CREATE INDEX tasks_list ON tasks (list_id, deleted_at, sort_order)',
  );
  final i1.Index tasksDay = i1.Index(
    'tasks_day',
    'CREATE INDEX tasks_day ON tasks (my_day_date, is_completed, deleted_at)',
  );
  final i1.Index tasksDue = i1.Index(
    'tasks_due',
    'CREATE INDEX tasks_due ON tasks (due_date, is_completed, deleted_at)',
  );
  final i1.Index stepsTask = i1.Index(
    'steps_task',
    'CREATE INDEX steps_task ON steps (task_id, deleted_at, sort_order)',
  );
  final i1.Index notesOrder = i1.Index(
    'notes_order',
    'CREATE INDEX notes_order ON note_pages (deleted_at, sort_order)',
  );
  final i1.Index noteBlocksPage = i1.Index(
    'note_blocks_page',
    'CREATE INDEX note_blocks_page ON note_blocks (page_id, deleted_at, sort_order)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get document =>
      columnsByName['document']! as i1.GeneratedColumn<String>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mix =>
      columnsByName['mix']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get masterVolume =>
      columnsByName['master_volume']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get muted =>
      columnsByName['muted']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mix',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'master_volume',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL DEFAULT 0.5',
      defaultValue: const i1.CustomExpression('0.5'),
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (muted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    lists,
    tasks,
    steps,
    reminderJobs,
    notePages,
    noteBlocks,
    customThemes,
    themeSettings,
    focusSoundscapes,
    focusSettings,
    focusSessions,
    tasksList,
    tasksDay,
    tasksDue,
    stepsTask,
    notesOrder,
    noteBlocksPage,
    focusSessionsStarted,
    focusSessionsTask,
  ];
  late final Shape0 lists = Shape0(
    source: i0.VersionedTable(
      entityName: 'lists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 tasks = Shape1(
    source: i0.VersionedTable(
      entityName: 'tasks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_4,
        _column_5,
        _column_6,
        _column_17,
        _column_7,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 steps = Shape2(
    source: i0.VersionedTable(
      entityName: 'steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_19,
        _column_9,
        _column_11,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reminderJobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'reminder_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 notePages = Shape4(
    source: i0.VersionedTable(
      entityName: 'note_pages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_24,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 noteBlocks = Shape5(
    source: i0.VersionedTable(
      entityName: 'note_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 customThemes = Shape6(
    source: i0.VersionedTable(
      entityName: 'custom_themes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_34, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 themeSettings = Shape7(
    source: i0.VersionedTable(
      entityName: 'theme_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(id = 1)',
        'CHECK((active_custom_theme_id IS NULL)!=(active_preset_id IS NULL))',
      ],
      columns: [_column_35, _column_36, _column_37, _column_38],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 focusSoundscapes = Shape8(
    source: i0.VersionedTable(
      entityName: 'focus_soundscapes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 focusSettings = Shape9(
    source: i0.VersionedTable(
      entityName: 'focus_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK(id = 1)',
        'CHECK(master_volume BETWEEN 0 AND 1)',
      ],
      columns: [_column_35, _column_39, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 focusSessions = Shape10(
    source: i0.VersionedTable(
      entityName: 'focus_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_42, _column_43, _column_44, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index tasksList = i1.Index(
    'tasks_list',
    'CREATE INDEX tasks_list ON tasks (list_id, deleted_at, sort_order)',
  );
  final i1.Index tasksDay = i1.Index(
    'tasks_day',
    'CREATE INDEX tasks_day ON tasks (my_day_date, is_completed, deleted_at)',
  );
  final i1.Index tasksDue = i1.Index(
    'tasks_due',
    'CREATE INDEX tasks_due ON tasks (due_date, is_completed, deleted_at)',
  );
  final i1.Index stepsTask = i1.Index(
    'steps_task',
    'CREATE INDEX steps_task ON steps (task_id, deleted_at, sort_order)',
  );
  final i1.Index notesOrder = i1.Index(
    'notes_order',
    'CREATE INDEX notes_order ON note_pages (deleted_at, sort_order)',
  );
  final i1.Index noteBlocksPage = i1.Index(
    'note_blocks_page',
    'CREATE INDEX note_blocks_page ON note_blocks (page_id, deleted_at, sort_order)',
  );
  final i1.Index focusSessionsStarted = i1.Index(
    'focus_sessions_started',
    'CREATE INDEX focus_sessions_started ON focus_sessions (started_at)',
  );
  final i1.Index focusSessionsTask = i1.Index(
    'focus_sessions_task',
    'CREATE INDEX focus_sessions_task ON focus_sessions (linked_task_id)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get linkedTaskId =>
      columnsByName['linked_task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finished =>
      columnsByName['finished']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get document =>
      columnsByName['document']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'linked_task_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finished',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (finished IN (0, 1))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
